#\DeclareLyXModule[pyweave->latex,fancyvrb.sty,color]{PyWeave}
#DescriptionBegin
#Embed Python code in LyX.
#DescriptionEnd
#Category: literate

Format 36
OutputType             literate
OutputFormat           pyweave

Input litinsets.inc

Counter chunk
    InitialValue 2
End

OutputType             literate
OutputFormat           pyweave

ClassOptions
	Other          "noae"
End


InsetLayout "Flex:Python expression"
	LabelString           "Python expr"
	LatexType             Command
	LaTexName             Pyexpr
	LyXType               Custom
	Decoration            Conglomerate
	Font
	  Color               latex
	  Family              typewriter
	EndFont
	LabelFont
	  Color               latex
	  Size                Small
	EndFont
	MultiPar              false
	PassThru              1
	ParbreakIsNewline     1
	Spellcheck	      0
	FreeSpacing           true
	ForceLTR              true
End


InsetLayout "Flex:Python Input File"
	LabelString           "Python Input File"
	LatexType             Command
	LaTexName             PythonInput
	LyXType               Custom
	Decoration            Classic
	Font
	  Color               latex
	  Family              typewriter
	EndFont
	LabelFont
	  Color               latex
	  Size                Small
	EndFont
	MultiPar              false
	PassThru              1
	ParbreakIsNewline     1
	Spellcheck	      0
	FreeSpacing           true
	ForceLTR              true
End

